### ISSUE TITLE
All available width of preview from right

### ISSUE THREAD

**Issue by ghost** [payalord/xZoom#31] opened 2017-12-25 08:32 UTC
Hello!
Is it possible to do this through the settings?
https://monosnap.com/file/tL32BikUBrlnxVFbPFQZWNPh2CCZJ2.png

This is a very small size, for buyers it is almost useless
https://monosnap.com/file/tGdvR5pptGbtYPRdvQMM1x03KcRCJ5.png

**Comment by payalord** [comment] 2017-12-25 15:49
Yes, you can try to use options: zoomWidth, zoomHeight to adjust the width and height of zoom view window.

For example, here on initialization step. I set view window width size to 600 pixels wide:
```javascript
$(".xzoom, .xzoom-gallery").xzoom({zoomWidth: 600});
```

Also you can check [xzoom-sandbox](https://github.com/payalord/xzoom-sandbox) repository for more examples, to get more familiar with xZoom. And feel free to download sandbox to experiment on it.

**Comment by ghost** [comment] 2017-12-26 00:35
Then the preview is not adaptive, as here
https://monosnap.com/file/hHhDUIS3eY2eBhfizeCNIRXBRUJf9p.png

On small pictures zoom works incomprehensibly
![2017-12-26_07 30 12](https://user-images.githubusercontent.com/1108013/34343822-b1e0886c-ea0e-11e7-8645-b3bed3b0e1c7.png)
![2017-12-26_07 31 14](https://user-images.githubusercontent.com/1108013/34343832-f8aff020-ea0e-11e7-9fa7-3d67f91fdce5.png)

**Comment by payalord** [comment] 2017-12-26 00:52
Difference between this one: https://monosnap.com/file/hHhDUIS3eY2eBhfizeCNIRXBRUJf9p.png
And the one you working on - is proportions. Their big zoomed image so big, that lens on their zoom is not going out of source image box. In case if you will have same proportions as they are, then there will be no problems.

But if you can't fit that requirement, then what you can do right now, is workaround:
```css
.xzoom-preview {
  background: white; /* <-- depends on what background color will be used on pictures */
}
.xzoom-source {
  overflow: hidden;
}
```

But I'm not sure that this exactly what you need in your case. Another solution possibly can be a fix via javascript. Which i need time to figure out how to create.

**Comment by payalord** [comment] 2017-12-26 08:37
I checked amazon and how they do their adaptive function. I think I'll create patch for this soon. In a couple days. So this issue will be fixed natively.

**Comment by payalord** [comment] 2017-12-26 23:32
I have added new option - lensCollision and released new version [1.0.9](https://github.com/payalord/xZoom/releases/tag/v1.0.9). by switching this option to "false" lens are free from collide on main image borders.

Later I will add example to sandbox with integration of xZoom exactly same way as it works on Amazon.

**Comment by ghost** [comment] 2017-12-28 13:58
Thank you so much!
Zoom like Amazon it's very cool!

**Comment by Miloti** [comment] 2018-01-02 15:36
Hello!
Is it possible to show img class="xzoom" multiple times? 
Here, I want to show only the xzoom something like this:
 <img class="xzoom" src="gallery/preview/1.jpg" xoriginal="gallery/original/1.jpg" />
 <img class="xzoom" src="gallery/preview/2.jpg" xoriginal="gallery/original/2.jpg" />
 <img class="xzoom" src="gallery/preview/3.jpg" xoriginal="gallery/original/3jpg" />
 <img class="xzoom" src="gallery/preview/4.jpg" xoriginal="gallery/original/4.jpg" />

The problem is I can only zoom the first image, the other images keep frozen (no zoom or anything)!
Mabybe do I need to write some javascript or some ID for xzoom? Please help,

Thanks :)

**Comment by payalord** [comment] 2018-08-20 01:22
Looks like option `lensCollision` and white background style must be helped. I will close this issue, in case if will be required to solve something else. Please open new one. Thanks.

**Closed as completed by payalord** 2018-08-20 01:22 UTC
Labels: support requested, in progress
