### ISSUE TITLE
Not working over modal

### ISSUE THREAD

**Issue by DesarrolloMA** [payalord/xZoom#79] opened 2024-02-02 16:21 UTC
Using a modal the xzoom apears in the principal page not in the modal. Can you help me ?

![image](https://github.com/payalord/xZoom/assets/58304580/eb77644f-fbcd-4d89-8dd0-f43c2a63a4d0)
![image](https://github.com/payalord/xZoom/assets/58304580/77798c06-7973-42ac-8748-d4d99afaa326)

**Comment by payalord** [comment] 2024-02-02 20:04
Can you replicate this issue on https://jsfiddle.net/ ?

**Comment by payalord** [comment] 2024-07-26 05:58
Closing due to no answer and that the issue is probably outdated.

**Closed as completed by payalord** 2024-07-26 05:58 UTC
